Hw2.3 HashSet
anticNVM/144.math.spbu-II pull request #10
Opened 2018-03-11 22:05 UTC by anticNVM

2018-03-11 22:10 UTC, anticNVM commented on homeWork 2/T3-HashSet/HashSetSource/HashSet.cs
> +        private class Buckets : IEnumerable
Этот класс затевался вообще для того, чтобы не писать в 2ух местах цикл for с инициализацией ячеек списком. Но вместе с этим я потерял некоторые, возможно полезные, методы массива. Как с точки зрения архитектуры и тп здесь правильно сделать?

2018-04-01 19:22 UTC, yurii-litvinov requested changes
В целом всё так, но как обычно, надо немного поправить

2018-04-01 19:22 UTC, yurii-litvinov commented on homeWork 2/T3-HashSet/HashSetSource/HashSet.cs
> +                throw new ValueIsAlreadyInSetException(
Не нужно перебрасывать то же исключение, портя ему сохранённый StackTrace. Если сильно хочется, лучше хотя бы в InnerException положить исходное исключение

2018-04-01 19:22 UTC, yurii-litvinov commented on homeWork 2/T3-HashSet/HashSetSource/HashSet.cs
> +            if (this.Factor > 1)
1 --- "магическая константа". Имеет смысл сделать её честной именованной константой, чтобы было понятно, что она значит, и было можно легко её поменять

2018-04-01 19:22 UTC, yurii-litvinov commented on homeWork 2/T3-HashSet/HashSetSource/HashSet.cs
> +            int index = Math.Abs(value.GetHashCode()) % _capacity;
Может быть, вычисление индекса имело бы смысл вынести в отдельный метод. Ибо оно повсюду

2018-04-01 19:22 UTC, yurii-litvinov commented on homeWork 2/T3-HashSet/HashSetSource/HashSet.cs
> +        private class Buckets : IEnumerable
Вы ж методами массива не пользуетесь, так что всё ок. Архитектура --- весьма гуманитарная наука, но такой приём, как оборачивание более сложной абстракции в более простую, используется довольно часто. Тут не факт, что это оправданно, ведь хеш-таблица по сути и есть штука для управления bucket-ами, а цикл for можно было бы вынести в отдельный метод. Но так тоже ок, почему нет.

2018-04-01 19:22 UTC, yurii-litvinov commented on homeWork 2/T3-HashSet/LinkedListSource/ILinkedList.cs
> +    public interface ILinkedList : IEnumerable
А почему именно связного списка? В этом интерфейсе вроде нет методов, специфичных для связного списка, даже наоборот, индексеры связный список не любит. Может, переименовать просто в IList?

2018-04-01 19:22 UTC, yurii-litvinov commented on homeWork 2/T3-HashSet/Tests/LinkedListTest.cs
> +        public void CountShoulReturnAmountOfElemnts()
Elemnts существенно менее читабельно, чем Elements :)

2018-04-24 06:52 UTC, yurii-litvinov approved these changes
Зачтена

2018-04-24 06:52 UTC, yurii-litvinov commented on homeWork 2/T3-HashSet/HashSetSource/HashSet.cs
> +                );
Так а тут та же печаль с перебрасыванием исключения с потерей стека вызовов

2018-04-27 21:01 UTC, merged