Hw4.1 Arithmetic Parse Tree
anticNVM/144.math.spbu-II pull request #13
Opened 2018-04-21 12:38 UTC by anticNVM

2018-05-18 08:40 UTC, yurii-litvinov requested changes

2018-05-18 08:40 UTC, yurii-litvinov commented on homeWork 4/T1-ArithmeticParseTree/ParseTreeSource/IParseTree.cs
> +    /// Интерфейс, реализующий ф-ть дерева разбора арифметического выражения для целых чисел
"ф-ть" :)

2018-05-18 08:40 UTC, yurii-litvinov commented on homeWork 4/T1-ArithmeticParseTree/ParseTreeSource/Node.cs
> +    public partial class ParseTree
Не, это не лучший способ применения partial. И нужен комментарий

2018-05-18 08:40 UTC, yurii-litvinov commented on homeWork 4/T1-ArithmeticParseTree/ParseTreeSource/Node.cs
> +        private class Node
Лучше сделать их обычными классами, не вложенными. Инкапсуляция хорошо, но ParseTree тогда получается слишком умным и большим. Можно эти классы в свой неймспейс вынести.

2018-05-18 08:40 UTC, yurii-litvinov commented on homeWork 4/T1-ArithmeticParseTree/ParseTreeSource/Node.cs
> +            public Node _rightNode;
И если не делать это private class-ом, то public-поля тут будут не в тему. Они и так не в тему, от этого класса предполагается наследоваться, так что уж очень много кода может испортить эти поля.

2018-05-18 08:40 UTC, yurii-litvinov commented on homeWork 4/T1-ArithmeticParseTree/ParseTreeSource/Node.cs
> +            public Node _rightNode;
И, кстати, для операндов эти поля бессмысленны, их лучше сдвинуть вниз по иерархии наследования в класс Operator

2018-05-18 08:40 UTC, yurii-litvinov commented on homeWork 4/T1-ArithmeticParseTree/ParseTreeSource/Node.cs
> +            public virtual int Evaluate() => throw new System.NotImplementedException("ой ой ой");
Да ну, лучше Evaluate сделать абстрактным

2018-05-18 08:40 UTC, yurii-litvinov commented on homeWork 4/T1-ArithmeticParseTree/ParseTreeSource/Operator.cs
> +                var bar = new ParseTree();
Создавать ParseTree только для того, чтобы получить операцию --- неэффективно и концептуально неправильно, принцип единственности ответственности же. Лучше отдельный класс "таблица операций", и передавать эту таблицу как параметр всем операторам при создании, и хранить в операторе ссылку на таблицу (при этоом сама таблица создаётся один раз в начале разбора). И тогда не надо будет хранить тут _operation, мы всегда можем достать операцию по коду символа из таблицы (что снижает риск неконсистентности, когда знак "+", а операция "-")

2018-05-18 08:40 UTC, yurii-litvinov commented on homeWork 4/T1-ArithmeticParseTree/ParseTreeSource/ParseTree.cs
> +        private sealed class MapOfOperations : Dictionary<string, Func<int, int, int>> { }
Так нельзя делать, потому что это не синоним типа, а новый класс, что может быть неожиданно для операций типа typeof, is и т.д. Для этого есть using: https://www.dotnetperls.com/using-alias

2018-05-18 08:40 UTC, yurii-litvinov commented on homeWork 4/T1-ArithmeticParseTree/ParseTreeSource/ParseTree.cs
> +    public static class EnumeratorExtension
Лучше в отдельный файл, и с комментарием.

2018-05-18 08:40 UTC, yurii-litvinov commented on homeWork 4/T1-ArithmeticParseTree/ParseTreeTest/ParseTreeTest.cs
> +
Лишняя пустая строчка (на самом деле даже две, перед "}" пустая скобка не ставится) :)

2018-06-04 21:45 UTC, anticNVM commented on homeWork 4/T1-ArithmeticParseTree/ParseTreeSource/Node.cs
> +        private class Node
С той реализацией построения дерева, что у меня сейчас, вроде нельзя это нормально реализовать, так что я оставил их приватными внутри ParseTree, но все остальное поправил

2018-06-04 21:52 UTC, anticNVM commented on homeWork 4/T1-ArithmeticParseTree/ParseTreeSource/Node.cs
> +            public Node _rightNode;
А можно ещё раз, как потомки могут испортить эти поля?)

2018-06-11 11:38 UTC, yurii-litvinov commented on homeWork 4/T1-ArithmeticParseTree/ParseTreeSource/ParseTree.cs
> +    public partial class ParseTree : IParseTree
partial не нужен

2018-06-11 11:38 UTC, yurii-litvinov commented on homeWork 4/T1-ArithmeticParseTree/ParseTreeSource/ParseTree.cs
> +        private abstract class Node
Можно было бы интерфейсом сделать, у него же нет ни поведения своего, ни состояния. Всегда когда есть выбор между абстрактным классом и интерфейсом, лучше интерфейсы

2018-06-11 11:38 UTC, yurii-litvinov commented on homeWork 4/T1-ArithmeticParseTree/ParseTreeSource/Node.cs
> +            public Node _rightNode;
Запишут туда null-ы, например

2018-06-11 11:41 UTC, yurii-litvinov approved these changes
Всё ок теперь, зачтена.

2018-06-11 11:41 UTC, yurii-litvinov commented on homeWork 4/T1-ArithmeticParseTree/ParseTreeSource/TableOfOperations.cs
> +    public class TableOfOperations
К ней бы комментарий ещё

2018-06-11 12:19 UTC, merged