Hw6.1 GuiCalculator
anticNVM/144.math.spbu-II pull request #14
Opened 2018-04-27 20:40 UTC by anticNVM

2018-04-27 20:43 UTC, anticNVM commented on homeWork 6/T1-GtkCalculator/CalculatorTests/IncorrectInputDataTests.cs
> +        public void TestCase(string expression, string message)
А можно сюда передавать и тип ошибки? Или для разных ошибок просто разные датасеты писать?

2018-04-27 20:46 UTC, anticNVM commented on homeWork 6/T1-GtkCalculator/CalculatorTests/IncorrectInputDataTests.cs
> +        public void TestCase(string expression, string message)
И тут вот этот непонятный варнинг (подчеркивает expression в аргументах и => в лямбде). Хоть на stackoverflow есть ответ на этот счет, но я все равно не особо понимаю, что здесь требуется

2018-04-27 20:56 UTC, anticNVM commented on homeWork 6/T1-GtkCalculator/CalculatorTests/CorrectInputDataTests.cs
> +        };
А тут варнинг для 2ого аргумента в TestCaseData: value type to reference type conversion causes boxing at call site (here), and unboxing at the callee-site. Consider using generics if applicable. В чем причины и как можно поправить?

2018-06-09 18:27 UTC, yurii-litvinov requested changes
Оно настолько не собирается под виндой, насколько это вообще возможно. И под линуксом, правда, тоже не собирается :) Зависимости не прописаны?

Вы же достаточно технологически продвинуты, чтобы Вас можно было попросить настроить билд на Travis или даже AppVeyor.

2018-06-09 18:27 UTC, yurii-litvinov commented on homeWork 6/T1-GtkCalculator/CalculatorSource/Calculator.cs
> +        public static double Evaluate(string expression)
Хотелось калькулятор наподобие виндового, разбирать выражение было не надо :)

2018-06-09 18:27 UTC, yurii-litvinov commented on homeWork 6/T1-GtkCalculator/CalculatorSource/Calculator.cs
> +        };
👍

2018-06-09 18:27 UTC, yurii-litvinov commented on homeWork 6/T1-GtkCalculator/CalculatorSource/Calculator.cs
> +                // если опретор
Опечатка :)

2018-06-09 18:27 UTC, yurii-litvinov commented on homeWork 6/T1-GtkCalculator/CalculatorSource/Calculator.cs
> +                            InvalidExpressionException.MessageTypes.MissedOpeningBracket]);
Это неплохо бы тоже отступом выделить

2018-06-09 18:27 UTC, yurii-litvinov commented on homeWork 6/T1-GtkCalculator/CalculatorTests/CorrectInputDataTests.cs
> +        };
Конструктор хочет object, но ему передаётся число, так что он вынужден его забоксить. Поправить, вроде бы, никак, можно отключить предупреждение: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives/preprocessor-pragma-warning

2019-03-24 15:28 UTC, merged