Hw5.2 Map Walker
anticNVM/144.math.spbu-II pull request #19
Opened 2018-06-10 23:50 UTC by anticNVM

2018-06-10 23:57 UTC, anticNVM commented on homeWork 5/T2-MapWalker/Source/Game/Game.cs
> +        protected Player _player;
Он тут protected только чтобы можно было тесты как-то писать. Мне почему-то кажется, что это не очень правильное решение, хотя лучше я пока не могу придумать

2018-06-11 12:26 UTC, yurii-litvinov requested changes
Очень круто (я бы даже сказал, что Вы перестарались), но надо код немного привести в порядок.

2018-06-11 12:26 UTC, yurii-litvinov commented on homeWork 5/T2-MapWalker/Program/Program.cs
> +                e is PlatformNotSupportedException
А чего бы его прямо так и не ловить? Просто `catch (PlatformNotSupportedException e)`?

2018-06-11 12:26 UTC, yurii-litvinov commented on homeWork 5/T2-MapWalker/Program/Program.cs
> +            }
Неплохо бы предусмотреть конфигурацию по умолчанию

2018-06-11 12:26 UTC, yurii-litvinov commented on homeWork 5/T2-MapWalker/Source/Game/Coordinates.cs
> +        }
Тогда и хеш-функцию надо переопределить, у равных объектов она не может быть разной

2018-06-11 12:26 UTC, yurii-litvinov commented on homeWork 5/T2-MapWalker/Source/Game/Game.cs
> +        protected Player _player;
Mock-объекты и внедрение зависимости через конструктор Game должно помочь

2018-06-11 12:26 UTC, yurii-litvinov commented on homeWork 5/T2-MapWalker/Source/Game/GameConfig.cs
> +        public string pathToMap { get; set; }
CamelCase please

2018-06-11 12:26 UTC, yurii-litvinov commented on homeWork 5/T2-MapWalker/Source/Loops/IMotionEventLoop.cs
> +        event EventHandler<MotionVectorEventArgs> Motion;
Тоже нужен комментарий

2018-06-11 12:26 UTC, yurii-litvinov commented on homeWork 5/T2-MapWalker/Source/Loops/IMotionEventLoop.cs
> +        event EventHandler<MotionVectorEventArgs> Motion;
Тоже нужен комментарий

2018-06-11 12:26 UTC, yurii-litvinov commented on homeWork 5/T2-MapWalker/Source/Game/Game.cs
> +            _player.DestinationReached += (object sender, EventArgs args) => _mainloop.Exit();
Прямая зависимость от mainloop архитектурно нехороша, лучше бы сделать третий объект, про который бы знали Game и MainLoop, и уже у него было бы свойство Exit. Весь пойнт этой домашки был в минимизации связности с помощью событий. Кстати, и Game мог MainLoop-у событие посылать.

2018-06-11 12:26 UTC, yurii-litvinov commented on homeWork 5/T2-MapWalker/Source/Map/IMap.cs
> +        /// <returns></returns>
А вот пустой тэг не нужен

2018-06-11 12:26 UTC, yurii-litvinov commented on homeWork 5/T2-MapWalker/Source/Map/Map.cs
> +        private void BuildMap(StreamReader inputStream, out Coordinates initPlayerCoords)
Зачем out-параметр, его ж можно просто обычно возвращать из метода

2018-06-11 12:26 UTC, yurii-litvinov commented on homeWork 5/T2-MapWalker/Source/Map/MapConfig.cs
> +        public IReadOnlyDictionary<string, char> Keywords { get; set; }
А зачем ему сеттеры? Конфиг мог бы сам себя грузить и инициализировать. Ну либо инициализироваться в конструкторе. Вряд ли в течение игры что-то из этого изменится.

2018-06-11 12:26 UTC, yurii-litvinov commented on homeWork 5/T2-MapWalker/Source/Player/Player.cs
> +    public class Player
Комментарий надо :)

2019-03-24 15:28 UTC, merged