Hw3.1 StackCalculator
anticNVM/144.math.spbu-II pull request #7
Opened 2018-03-01 19:56 UTC by anticNVM

2018-03-08 12:45 UTC, yurii-litvinov requested changes
В целом всё так, но как-то очень неаккуратно реализовано. Поправьте, пожалуйста.

2018-03-08 12:45 UTC, yurii-litvinov commented on homeWork 3/T1-StackCalculator/StackCalculator/ArrayStack.cs
> +        private static readonly int _defaultSize = 10;
Его имело бы смысл сделать не readonly, а const --- отличие в том, что значение поля const должно быть известно во время компиляции, и тогда компилятор сам может выполнить подстановку, не выделяя для хранения поля память.

2018-03-08 12:45 UTC, yurii-litvinov commented on homeWork 3/T1-StackCalculator/StackCalculator/ArrayStack.cs
> +                size = _defaultSize;
Я б тут исключение бросил, ведь если вызывающий код пытается сделать что-то такое, уже что-то пошло не так.

2018-03-08 12:45 UTC, yurii-litvinov commented on homeWork 3/T1-StackCalculator/StackCalculator/ArrayStack.cs
> +        }
Это можно записать просто как `public int Count => _positionAfterTop;` --- то же самое по смыслу, но короче

2018-03-08 12:45 UTC, yurii-litvinov commented on homeWork 3/T1-StackCalculator/StackCalculator/LinkedStack.cs
> +            head = null;
Они и так нули, дополнительная инициализация не требуется

2018-03-08 12:45 UTC, yurii-litvinov commented on homeWork 3/T1-StackCalculator/StackCalculator/Program.cs
> +                    calc = null;
Чтобы потом упасть с непонятным NullReferenceException? :)

2018-03-08 12:45 UTC, yurii-litvinov commented on homeWork 3/T1-StackCalculator/StackCalculator/StackCalc.cs
> +                    }
Это лучше через ? ... : ... записать

2018-03-08 12:45 UTC, yurii-litvinov commented on homeWork 3/T1-StackCalculator/StackCalculator/StackCalc.cs
> +            }
И тут

2018-03-08 12:45 UTC, yurii-litvinov commented on homeWork 3/T1-StackCalculator/StackCalculator.Test/ArrayStackTest.cs
> +    }
А остальные методы ArrayStack-а?

2018-03-08 12:45 UTC, yurii-litvinov commented on homeWork 3/T1-StackCalculator/StackCalculator/ArrayStack.cs
> +            }
Можно через тернарный оператор записать. И даже через expression-bodied-синтаксис. Очень многословно :)

2018-03-08 12:45 UTC, yurii-litvinov commented on homeWork 3/T1-StackCalculator/StackCalculator/LinkedStack.cs
> +            }
Можно просто head и Count сбросить, обходить весь стек необязательно

2018-03-10 18:25 UTC, anticNVM commented on homeWork 3/T1-StackCalculator/StackCalculator/Program.cs
> +            catch (Exceptions.InvalidExpressionException e)
Тут в обоих catch`ах мы делаем одно и то же. Мне кажется, что это не очень правильно)

2018-03-10 18:31 UTC, anticNVM commented on homeWork 3/T1-StackCalculator/StackCalculator/Program.cs
> +            catch (Exceptions.InvalidExpressionException e)
Тут вообще можно сделать что-то полезное, кроме того, что вывести информацию об исключении в консоль?

2018-04-01 15:33 UTC, yurii-litvinov approved these changes
Окей, зачтена

2018-04-01 15:33 UTC, yurii-litvinov commented on homeWork 3/T1-StackCalculator/StackCalculator/Program.cs
> +            catch (Exceptions.InvalidExpressionException e)
Вот тут подробный пост про то, что делать, если два исключения обрабатываются одинаково: https://stackoverflow.com/questions/136035/catch-multiple-exceptions-at-once. Полезное --- вряд ли, разве что попросить пользователя ввести выражение ещё раз

2018-04-01 15:33 UTC, yurii-litvinov commented on homeWork 3/T1-StackCalculator/Exceptions/InvalidExpressionException.cs
> +    public class InvalidExpressionException : Exception
Этой штуке тоже нужен комментарий

2018-04-01 15:33 UTC, yurii-litvinov commented on homeWork 3/T1-StackCalculator/StackCalculator.Test/ArrayStackTest.cs
> +            bool isEmpty = _stack.IsEmpty();;
Точка с запятой лишняя :)

2018-04-01 15:33 UTC, yurii-litvinov commented on homeWork 3/T1-StackCalculator/StackCalculator.Test/ArrayStackTest.cs
> +            bool isEmpty = _stack.IsEmpty();;
И тут

2018-04-01 15:33 UTC, yurii-litvinov commented on homeWork 3/T1-StackCalculator/StackCalculator/ICalculator.cs
> +        /// <returns>Целочистенный результат выражения.`</returns>
"Целочистенный", опечатка

2018-04-01 15:33 UTC, yurii-litvinov commented on homeWork 3/T1-StackCalculator/StackCalculator/IStack.cs
> +        public static bool IsEmpty(this IStack obj)
Это лучше было сделать в самом стеке, всё-таки метод концептуально принадлежит ему

2018-04-01 15:33 UTC, yurii-litvinov commented on homeWork 3/T1-StackCalculator/StackCalculator/LinkedStack.cs
> +    /// Класс, реализующий стек на остнове связного списка
"остнове", опечатка

2018-04-27 21:00 UTC, merged